# Dependencies installed by bootstrap.sh. Homebrew itself, Git, and Zsh remain
# external prerequisites.

brew "atuin"
brew "btop"
brew "dockutil"
brew "duti"
brew "fzf"
brew "gh"
brew "jq"
brew "meta-package-manager"
brew "mise"
brew "mole"
brew "ripgrep"
brew "shellcheck"
brew "skills"
brew "starship"
brew "stow"
brew "tailscale"
brew "tmux"
brew "x-cmd"
brew "yazi"
brew "zoxide"

tap "hasansezertasan/tap"
brew "hasansezertasan/tap/cobo"
brew "hasansezertasan/tap/hwid"
brew "hasansezertasan/tap/nur"
brew "hasansezertasan/tap/ocom"
brew "hasansezertasan/tap/olink"
brew "hasansezertasan/tap/peta"
